#!/bin/sh

INSTALLPATH=/opt/certgen/certs
CONFIG=$INSTALLPATH/server/config
FILES=$CONFIG/*.conf
OUTPUT=$INSTALLPATH/server/generated
CAKEY=$INSTALLPATH/CA/generated/myCA.key
CACRT=$INSTALLPATH/CA/generated/myCA.crt
CASERIAL=$INSTALLPATH/CA/.serial

for FILE in $FILES
do
    FILENAME=$(basename "$FILE" .conf)
    echo "Processing $FILENAME..."
    
    if ! [ -r $OUTPUT/$FILENAME.key ]
    then
        echo "Generating: $FILENAME.key"
        openssl genrsa -out $OUTPUT/$FILENAME.key 2048
    else
        echo "$FILENAME.key found -> Generating certificate request"
    fi
    
    echo "Generating certificate request: $FILENAME.csr"
    openssl req -key $OUTPUT/$FILENAME.key -new -out $OUTPUT/$FILENAME.csr -config $CONFIG/$FILENAME.conf
    
    echo "Generating certificate: $FILENAME.crt"
    openssl x509 -req -sha256 -in $OUTPUT/$FILENAME.csr -out $OUTPUT/$FILENAME.crt -CA $CACRT -CAkey $CAKEY -days 365 -CAcreateserial -CAserial $CASERIAL -extensions v3 -extfile $CONFIG/$FILENAME.conf
    
    echo "Generating combined key: $FILENAME.pem"
    cat $OUTPUT/$FILENAME.crt > $OUTPUT/$FILENAME.pem
    cat $OUTPUT/$FILENAME.key >> $OUTPUT/$FILENAME.pem
    
done